### PR TITLE
Rename to draft-ietf-jsonpath-base

### PR DESCRIPTION
**Pull request by mkmik**
* Updated year
* Updated Marko's affiliation
* Pin versions in Dockerfiles in order to limit unrelated diffs in PRs

Preview visible at: https://mkmik.github.io/internet-draft/

### CODE REVIEW

**Review by timbray — COMMENTED** [review]
First time I've looked at this particular flavor of PR, but generally LGTM.

Question: what's all the base64 in the generated XML?

**Comment by mkmik** [comment]
> Question: what's all the base64 in the generated XML?

The markdown source (compressed) out of which the xml file is generated.

**Review by goessner — APPROVED** [review]
Cannot say a lot here. Seems to be consistent and ok.

**Review by glyn — COMMENTED** [review]
LGTM, thanks.

**Comment by cabo** [comment]
> Question: what's all the base64 in the generated XML?

The markdown source, as that cannot be submitted to the datatracker yet.

**Pull request merged**
